const picks = {
	annie: [
		['Kentucky', 'Florida', 'Mississippi State*', 'Arkansas', 'Alabama', 'Tennessee', 'Texas A&M'],
		['Florida', 'Tennessee', 'Alabama', 'Kentucky*', 'Arkansas', 'Georgia', 'LSU'],
		['Alabama', 'Arkansas*', 'Florida', 'Georgia', 'Kentucky', 'LSU', 'Vanderbilt'],
		['Georgia', 'Ole Miss', 'South Carolina*', 'Tennessee', 'Texas A&M'],
		['Alabama', 'Ole Miss*', 'Kentucky', 'South Carolina'],
		['LSU', 'Ole Miss', 'Alabama', 'Texas A&M', 'Georgia', 'Florida'],
		['Florida*', 'Vanderbilt', 'Texas A&M', 'Arkansas'],
		['Kentucky', 'Arkansas*', 'Ole Miss'],
	],
	carolyn: [
		['Auburn', 'Florida', 'LSU', 'Arkansas*', 'Alabama', 'South Carolina', 'Texas A&M'],
		['Florida', 'Tennessee', 'Alabama', 'Ole Miss', 'Arkansas*', 'Auburn', 'LSU'],
		['Alabama', 'Arkansas*', 'Florida', 'Georgia', 'Kentucky', 'LSU', 'South Carolina'],
		['Alabama', 'Arkansas*', 'Auburn', 'Kentucky', 'Mississippi State'],
		['Alabama', 'Ole Miss', 'Kentucky', 'South Carolina*'],
		['Auburn', 'Vanderbilt', 'Alabama', 'Arkansas*', 'Kentucky', 'Florida'],
		['Georgia', 'Vanderbilt', 'Texas A&M', 'Arkansas*'],
		['Vanderbilt', 'Arkansas*', 'South Carolina'],
	],
	rudy: [
		['Kentucky', 'Florida', 'LSU', 'Arkansas*', 'Alabama', 'Tennessee', 'Texas A&M'],
		['Florida', 'Tennessee', 'Alabama', 'Kentucky', 'Arkansas*', 'Auburn', 'LSU'],
		['Alabama', 'Arkansas*', 'Florida', 'Georgia', 'Mississippi State', 'LSU', 'Vanderbilt'],
		['Alabama', 'Arkansas', 'South Carolina*', 'Tennessee', 'Texas A&M'],
		['Alabama', 'Ole Miss*', 'Kentucky', 'South Carolina'],
		['LSU', 'Ole Miss', 'Alabama', 'Arkansas*', 'Georgia', 'Missouri'],
		['Georgia', 'Mississippi State', 'Texas A&M', 'Arkansas*'],
		['Kentucky', 'Arkansas*', 'Ole Miss'],
	],
	jenny: [
		['Auburn', 'Ole Miss', 'LSU', 'Arkansas*', 'Missouri', 'South Carolina', 'Texas A&M'],
		['Florida', 'Tennessee', 'Alabama', 'Kentucky', 'Mississippi State', 'Georgia', 'Vanderbilt*'],
		['Ole Miss', 'Auburn', 'Texas A&M*', 'Georgia', 'Kentucky', 'LSU', 'Vanderbilt'],
		['Alabama', 'Arkansas*', 'South Carolina', 'Tennessee', 'Mississippi State'],
		['Tennessee', 'Ole Miss*', 'Missouri', 'LSU'],
		['Auburn*', 'Vanderbilt', 'Alabama', 'Texas A&M', 'Kentucky', 'Florida'],
		['Florida', 'Mississippi State', 'South Carolina', 'Arkansas*'],
		['Kentucky', 'Florida', 'Ole Miss'],
	],
	blake: [
		['Kentucky*', 'Florida', 'LSU', 'Georgia', 'Alabama', 'South Carolina', 'Texas A&M'],
		['Florida', 'Tennessee', 'Alabama', 'Kentucky*', 'Mississippi State', 'Auburn', 'LSU'],
		['Alabama', 'Auburn', '', 'Tennessee*', 'Kentucky', 'LSU', 'South Carolina'],
		['Georgia', 'Ole Miss', 'Auburn', 'Tennessee', 'Mississippi State*'],
		['', '', '', ''],
		['Auburn', 'Ole Miss', 'Alabama', 'Arkansas', 'Georgia', 'Missouri*'],
		['', '', '', ''],
		['Kentucky', 'Arkansas*', 'Ole Miss'],
	],
	abernathy: [
		['Auburn', 'Ole Miss*', 'LSU', 'Georgia', 'Alabama', 'Tennessee', 'Texas A&M'],
		['Florida', 'Tennessee', 'Alabama', 'Ole Miss', 'Mississippi State', 'Auburn*', 'LSU'],
		['Alabama', 'Auburn', 'Florida', 'Georgia', 'Kentucky', 'LSU', 'Vanderbilt*'],
		['Georgia', 'Arkansas*', 'Auburn', 'Tennessee', 'Texas A&M'],
		['Alabama', 'Auburn', 'Missouri*', 'South Carolina'],
		['Auburn*', 'Ole Miss', 'Alabama', 'Texas A&M', 'Georiga', 'Missouri'],
		['Georgia', 'Mississippi State', 'Texas A&M', 'Arkansas*'],
		['Kentucky', 'Florida', 'Ole Miss'],
	]
}